Module DataHora

    Sub Main()
        Dim Arabe As New Globalization.HijriCalendar
        Dim Japones As New Globalization.JapaneseCalendar
        Dim Koreano As New Globalization.KoreanCalendar
        Dim Hoje As New DateTime
        Hoje = DateTime.Now()
        Console.WriteLine()
        Console.WriteLine("VB .NET TRABALHANDO COM DIVERSAS CULTURAS")
        Console.WriteLine("_________________________________________")
        Console.WriteLine()
        Console.WriteLine("No calendário Ocidental hoje é dia..: " & FormatDateTime(Today, DateFormat.ShortDate))
        Console.WriteLine("No calendário Árabe hoje é dia......: " & Arabe.GetDayOfMonth(Today) & "/" & Arabe.GetMonth(Today) & "/" & Arabe.GetYear(Today))
        Console.WriteLine("No calendário Japão hoje é dia......: " & Japones.GetDayOfMonth(Today) & "/" & Japones.GetMonth(Today) & "/" & Japones.GetYear(Today))
        Console.WriteLine("No calendário Coreano hoje é dia....: " & Koreano.GetDayOfMonth(Today) & "/" & Koreano.GetMonth(Today) & "/" & Koreano.GetYear(Today))
        Console.WriteLine()
        Console.WriteLine("Pressione ENTER...")
        Console.ReadLine()
        Console.WriteLine("FORMATOS DE DATAS E HORAS")
        Console.WriteLine("_________________________________________")
        Console.WriteLine()
        Console.WriteLine("A data de hoje é: " & Hoje.ToString)
        Console.WriteLine("Sua data geral..: " & FormatDateTime(Hoje, DateFormat.GeneralDate))
        Console.WriteLine("Sua data longa..: " & FormatDateTime(Hoje, DateFormat.LongDate))
        Console.WriteLine("Sua hora longa..: " & FormatDateTime(Hoje, DateFormat.LongTime))
        Console.WriteLine("Sua data curta..: " & FormatDateTime(Hoje, DateFormat.ShortDate))
        Console.WriteLine("Sua hora curta..: " & FormatDateTime(Hoje, DateFormat.ShortTime))
        Console.WriteLine()
        Console.WriteLine("Pressione ENTER...")
        Console.ReadLine()
        Console.WriteLine("OUTROS FORMATOS DE DATAS")
        Console.WriteLine("_________________________________________")
        Console.WriteLine()
        Console.WriteLine("FORMATOS PARA DIA")
        Console.WriteLine("d...: " & Format(Hoje, "d"))
        Console.WriteLine("dd..: " & Format(Hoje, "dd"))
        Console.WriteLine("ddd.: " & Format(Hoje, "ddd"))
        Console.WriteLine("dddd: " & Format(Hoje, "dddd"))
        Console.WriteLine()
        Console.WriteLine("FORMATOS PARA MÊS")
        Console.WriteLine("M...: " & Format(Hoje, "M"))
        Console.WriteLine("MM..: " & Format(Hoje, "MM"))
        Console.WriteLine("MMM.: " & Format(Hoje, "MMM"))
        Console.WriteLine("MMMM: " & Format(Hoje, "MMMM"))
        Console.WriteLine()
        Console.WriteLine("FORMATOS PARA ANO")
        Console.WriteLine("y...: " & Format(Hoje, "y"))
        Console.WriteLine("yy..: " & Format(Hoje, "yy"))
        Console.WriteLine("yyyy: " & Format(Hoje, "yyyy"))
        Console.WriteLine()
        Console.WriteLine("Pressione ENTER...")
        Console.ReadLine()
        Console.WriteLine("OUTROS FORMATOS DE HORAS")
        Console.WriteLine("_________________________________________")
        Console.WriteLine()
        Console.WriteLine("HORA ATUAL (hh:mm:ss): " & Format(Hoje, "hh:mm:ss"))
        Console.WriteLine()
        Console.WriteLine("FORMATOS PARA HORA")
        Console.WriteLine("hh: " & Format(Hoje, "hh"))
        Console.WriteLine("HH: " & Format(Hoje, "HH"))
        Console.WriteLine()
        Console.WriteLine("FORMATO PARA MINUTOS")
        Console.WriteLine("mm: " & Format(Hoje, "mm"))
        Console.WriteLine()
        Console.WriteLine("FORMATO PARA SEGUNDOS")
        Console.WriteLine("ss: " & Format(Hoje, "ss"))
        Console.ReadLine()
        Try
            Console.WriteLine("Número de dias no mês atual: " & _
                DateTime.DaysInMonth(DateTime.Now.Year, DateTime.Now.Month).ToString)
        Catch ex As ArgumentOutOfRangeException
            Console.WriteLine("O mês informado é inválido.")
        Catch ex As Exception
            Console.WriteLine("Ocorreu um erro")
        End Try
        Console.WriteLine(IIf(DateTime.IsLeapYear(Today.Year), "Esse ano é bissexto", _
            "Esse ano não é bissexto"))
        Console.WriteLine("A máxima data suportada é: " & DateTime.MaxValue.ToString)
        Console.WriteLine("A mínima data suportada é: " & DateTime.MinValue.ToString)
        Console.ReadLine()
    End Sub

End Module
