'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.42
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System


<System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0"),  _
 Serializable(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.ComponentModel.ToolboxItem(true),  _
 System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema"),  _
 System.Xml.Serialization.XmlRootAttribute("ClienteDataSet"),  _
 System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")>  _
Partial Public Class ClienteDataSet
    Inherits System.Data.DataSet
    
    Private tableCliente As ClienteDataTable
    
    Private _schemaSerializationMode As System.Data.SchemaSerializationMode = System.Data.SchemaSerializationMode.IncludeSchema
    
    <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Public Sub New()
        MyBase.New
        Me.BeginInit
        Me.InitClass
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler MyBase.Tables.CollectionChanged, schemaChangedHandler
        AddHandler MyBase.Relations.CollectionChanged, schemaChangedHandler
        Me.EndInit
    End Sub
    
    <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Sub New(ByVal info As System.Runtime.Serialization.SerializationInfo, ByVal context As System.Runtime.Serialization.StreamingContext)
        MyBase.New(info, context, false)
        If (Me.IsBinarySerialized(info, context) = true) Then
            Me.InitVars(false)
            Dim schemaChangedHandler1 As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
            AddHandler Me.Tables.CollectionChanged, schemaChangedHandler1
            AddHandler Me.Relations.CollectionChanged, schemaChangedHandler1
            Return
        End If
        Dim strSchema As String = CType(info.GetValue("XmlSchema", GetType(String)),String)
        If (Me.DetermineSchemaSerializationMode(info, context) = System.Data.SchemaSerializationMode.IncludeSchema) Then
            Dim ds As System.Data.DataSet = New System.Data.DataSet
            ds.ReadXmlSchema(New System.Xml.XmlTextReader(New System.IO.StringReader(strSchema)))
            If (Not (ds.Tables("Cliente")) Is Nothing) Then
                MyBase.Tables.Add(New ClienteDataTable(ds.Tables("Cliente")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.ReadXmlSchema(New System.Xml.XmlTextReader(New System.IO.StringReader(strSchema)))
        End If
        Me.GetSerializationData(info, context)
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler MyBase.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    <System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     System.ComponentModel.Browsable(false),  _
     System.ComponentModel.DesignerSerializationVisibility(System.ComponentModel.DesignerSerializationVisibility.Content)>  _
    Public ReadOnly Property Cliente() As ClienteDataTable
        Get
            Return Me.tableCliente
        End Get
    End Property
    
    <System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     System.ComponentModel.BrowsableAttribute(true),  _
     System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Visible)>  _
    Public Overrides Property SchemaSerializationMode() As System.Data.SchemaSerializationMode
        Get
            Return Me._schemaSerializationMode
        End Get
        Set
            Me._schemaSerializationMode = value
        End Set
    End Property
    
    <System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)>  _
    Public Shadows ReadOnly Property Tables() As System.Data.DataTableCollection
        Get
            Return MyBase.Tables
        End Get
    End Property
    
    <System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)>  _
    Public Shadows ReadOnly Property Relations() As System.Data.DataRelationCollection
        Get
            Return MyBase.Relations
        End Get
    End Property
    
    <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Overrides Sub InitializeDerivedDataSet()
        Me.BeginInit
        Me.InitClass
        Me.EndInit
    End Sub
    
    <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Public Overrides Function Clone() As System.Data.DataSet
        Dim cln As ClienteDataSet = CType(MyBase.Clone,ClienteDataSet)
        cln.InitVars
        cln.SchemaSerializationMode = Me.SchemaSerializationMode
        Return cln
    End Function
    
    <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Overrides Function ShouldSerializeTables() As Boolean
        Return false
    End Function
    
    <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Overrides Function ShouldSerializeRelations() As Boolean
        Return false
    End Function
    
    <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Overrides Sub ReadXmlSerializable(ByVal reader As System.Xml.XmlReader)
        If (Me.DetermineSchemaSerializationMode(reader) = System.Data.SchemaSerializationMode.IncludeSchema) Then
            Me.Reset
            Dim ds As System.Data.DataSet = New System.Data.DataSet
            ds.ReadXml(reader)
            If (Not (ds.Tables("Cliente")) Is Nothing) Then
                MyBase.Tables.Add(New ClienteDataTable(ds.Tables("Cliente")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.ReadXml(reader)
            Me.InitVars
        End If
    End Sub
    
    <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Overrides Function GetSchemaSerializable() As System.Xml.Schema.XmlSchema
        Dim stream As System.IO.MemoryStream = New System.IO.MemoryStream
        Me.WriteXmlSchema(New System.Xml.XmlTextWriter(stream, Nothing))
        stream.Position = 0
        Return System.Xml.Schema.XmlSchema.Read(New System.Xml.XmlTextReader(stream), Nothing)
    End Function
    
    <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Friend Overloads Sub InitVars()
        Me.InitVars(true)
    End Sub
    
    <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Friend Overloads Sub InitVars(ByVal initTable As Boolean)
        Me.tableCliente = CType(MyBase.Tables("Cliente"),ClienteDataTable)
        If (initTable = true) Then
            If (Not (Me.tableCliente) Is Nothing) Then
                Me.tableCliente.InitVars
            End If
        End If
    End Sub
    
    <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Private Sub InitClass()
        Me.DataSetName = "ClienteDataSet"
        Me.Prefix = ""
        Me.Namespace = "http://tempuri.org/ClienteDataSet.xsd"
        Me.EnforceConstraints = true
        Me.SchemaSerializationMode = System.Data.SchemaSerializationMode.IncludeSchema
        Me.tableCliente = New ClienteDataTable
        MyBase.Tables.Add(Me.tableCliente)
    End Sub
    
    <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Private Function ShouldSerializeCliente() As Boolean
        Return false
    End Function
    
    <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Private Sub SchemaChanged(ByVal sender As Object, ByVal e As System.ComponentModel.CollectionChangeEventArgs)
        If (e.Action = System.ComponentModel.CollectionChangeAction.Remove) Then
            Me.InitVars
        End If
    End Sub
    
    <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Public Shared Function GetTypedDataSetSchema(ByVal xs As System.Xml.Schema.XmlSchemaSet) As System.Xml.Schema.XmlSchemaComplexType
        Dim ds As ClienteDataSet = New ClienteDataSet
        Dim type As System.Xml.Schema.XmlSchemaComplexType = New System.Xml.Schema.XmlSchemaComplexType
        Dim sequence As System.Xml.Schema.XmlSchemaSequence = New System.Xml.Schema.XmlSchemaSequence
        xs.Add(ds.GetSchemaSerializable)
        Dim any As System.Xml.Schema.XmlSchemaAny = New System.Xml.Schema.XmlSchemaAny
        any.Namespace = ds.Namespace
        sequence.Items.Add(any)
        type.Particle = sequence
        Return type
    End Function
    
    Public Delegate Sub ClienteRowChangeEventHandler(ByVal sender As Object, ByVal e As ClienteRowChangeEvent)
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0"),  _
     System.Serializable(),  _
     System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")>  _
    Partial Public Class ClienteDataTable
        Inherits System.Data.DataTable
        Implements System.Collections.IEnumerable
        
        Private columnCodigoCliente As System.Data.DataColumn
        
        Private columnNome As System.Data.DataColumn
        
        Private columnEndereco As System.Data.DataColumn
        
        Private columnCidade As System.Data.DataColumn
        
        Private columnBairro As System.Data.DataColumn
        
        Private columnEstado As System.Data.DataColumn
        
        Private columnCEP As System.Data.DataColumn
        
        Private columnTelefone As System.Data.DataColumn
        
        Private columnEMail As System.Data.DataColumn
        
        Private columnNacimento As System.Data.DataColumn
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub New()
            MyBase.New
            Me.TableName = "Cliente"
            Me.BeginInit
            Me.InitClass
            Me.EndInit
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Friend Sub New(ByVal table As System.Data.DataTable)
            MyBase.New
            Me.TableName = table.TableName
            If (table.CaseSensitive <> table.DataSet.CaseSensitive) Then
                Me.CaseSensitive = table.CaseSensitive
            End If
            If (table.Locale.ToString <> table.DataSet.Locale.ToString) Then
                Me.Locale = table.Locale
            End If
            If (table.Namespace <> table.DataSet.Namespace) Then
                Me.Namespace = table.Namespace
            End If
            Me.Prefix = table.Prefix
            Me.MinimumCapacity = table.MinimumCapacity
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Sub New(ByVal info As System.Runtime.Serialization.SerializationInfo, ByVal context As System.Runtime.Serialization.StreamingContext)
            MyBase.New(info, context)
            Me.InitVars
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property CodigoClienteColumn() As System.Data.DataColumn
            Get
                Return Me.columnCodigoCliente
            End Get
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property NomeColumn() As System.Data.DataColumn
            Get
                Return Me.columnNome
            End Get
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property EnderecoColumn() As System.Data.DataColumn
            Get
                Return Me.columnEndereco
            End Get
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property CidadeColumn() As System.Data.DataColumn
            Get
                Return Me.columnCidade
            End Get
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property BairroColumn() As System.Data.DataColumn
            Get
                Return Me.columnBairro
            End Get
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property EstadoColumn() As System.Data.DataColumn
            Get
                Return Me.columnEstado
            End Get
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property CEPColumn() As System.Data.DataColumn
            Get
                Return Me.columnCEP
            End Get
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property TelefoneColumn() As System.Data.DataColumn
            Get
                Return Me.columnTelefone
            End Get
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property EMailColumn() As System.Data.DataColumn
            Get
                Return Me.columnEMail
            End Get
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property NacimentoColumn() As System.Data.DataColumn
            Get
                Return Me.columnNacimento
            End Get
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         System.ComponentModel.Browsable(false)>  _
        Public ReadOnly Property Count() As Integer
            Get
                Return Me.Rows.Count
            End Get
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Default ReadOnly Property Item(ByVal index As Integer) As ClienteRow
            Get
                Return CType(Me.Rows(index),ClienteRow)
            End Get
        End Property
        
        Public Event ClienteRowChanging As ClienteRowChangeEventHandler
        
        Public Event ClienteRowChanged As ClienteRowChangeEventHandler
        
        Public Event ClienteRowDeleting As ClienteRowChangeEventHandler
        
        Public Event ClienteRowDeleted As ClienteRowChangeEventHandler
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Overloads Sub AddClienteRow(ByVal row As ClienteRow)
            Me.Rows.Add(row)
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Overloads Function AddClienteRow(ByVal Nome As String, ByVal Endereco As String, ByVal Cidade As String, ByVal Bairro As String, ByVal Estado As String, ByVal CEP As String, ByVal Telefone As String, ByVal EMail As String, ByVal Nacimento As Date) As ClienteRow
            Dim rowClienteRow As ClienteRow = CType(Me.NewRow,ClienteRow)
            rowClienteRow.ItemArray = New Object() {Nothing, Nome, Endereco, Cidade, Bairro, Estado, CEP, Telefone, EMail, Nacimento}
            Me.Rows.Add(rowClienteRow)
            Return rowClienteRow
        End Function
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function FindByCodigoCliente(ByVal CodigoCliente As Integer) As ClienteRow
            Return CType(Me.Rows.Find(New Object() {CodigoCliente}),ClienteRow)
        End Function
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Overridable Function GetEnumerator() As System.Collections.IEnumerator Implements System.Collections.IEnumerable.GetEnumerator
            Return Me.Rows.GetEnumerator
        End Function
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Overrides Function Clone() As System.Data.DataTable
            Dim cln As ClienteDataTable = CType(MyBase.Clone,ClienteDataTable)
            cln.InitVars
            Return cln
        End Function
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Function CreateInstance() As System.Data.DataTable
            Return New ClienteDataTable
        End Function
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Friend Sub InitVars()
            Me.columnCodigoCliente = MyBase.Columns("CodigoCliente")
            Me.columnNome = MyBase.Columns("Nome")
            Me.columnEndereco = MyBase.Columns("Endereco")
            Me.columnCidade = MyBase.Columns("Cidade")
            Me.columnBairro = MyBase.Columns("Bairro")
            Me.columnEstado = MyBase.Columns("Estado")
            Me.columnCEP = MyBase.Columns("CEP")
            Me.columnTelefone = MyBase.Columns("Telefone")
            Me.columnEMail = MyBase.Columns("EMail")
            Me.columnNacimento = MyBase.Columns("Nacimento")
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Private Sub InitClass()
            Me.columnCodigoCliente = New System.Data.DataColumn("CodigoCliente", GetType(Integer), Nothing, System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnCodigoCliente)
            Me.columnNome = New System.Data.DataColumn("Nome", GetType(String), Nothing, System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnNome)
            Me.columnEndereco = New System.Data.DataColumn("Endereco", GetType(String), Nothing, System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnEndereco)
            Me.columnCidade = New System.Data.DataColumn("Cidade", GetType(String), Nothing, System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnCidade)
            Me.columnBairro = New System.Data.DataColumn("Bairro", GetType(String), Nothing, System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnBairro)
            Me.columnEstado = New System.Data.DataColumn("Estado", GetType(String), Nothing, System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnEstado)
            Me.columnCEP = New System.Data.DataColumn("CEP", GetType(String), Nothing, System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnCEP)
            Me.columnTelefone = New System.Data.DataColumn("Telefone", GetType(String), Nothing, System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnTelefone)
            Me.columnEMail = New System.Data.DataColumn("EMail", GetType(String), Nothing, System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnEMail)
            Me.columnNacimento = New System.Data.DataColumn("Nacimento", GetType(Date), Nothing, System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnNacimento)
            Me.Constraints.Add(New System.Data.UniqueConstraint("Constraint1", New System.Data.DataColumn() {Me.columnCodigoCliente}, true))
            Me.columnCodigoCliente.AutoIncrement = true
            Me.columnCodigoCliente.AllowDBNull = false
            Me.columnCodigoCliente.ReadOnly = true
            Me.columnCodigoCliente.Unique = true
            Me.columnNome.AllowDBNull = false
            Me.columnNome.MaxLength = 50
            Me.columnEndereco.AllowDBNull = false
            Me.columnEndereco.MaxLength = 50
            Me.columnCidade.AllowDBNull = false
            Me.columnCidade.MaxLength = 50
            Me.columnBairro.AllowDBNull = false
            Me.columnBairro.MaxLength = 30
            Me.columnEstado.AllowDBNull = false
            Me.columnEstado.MaxLength = 20
            Me.columnCEP.AllowDBNull = false
            Me.columnCEP.MaxLength = 10
            Me.columnTelefone.AllowDBNull = false
            Me.columnTelefone.MaxLength = 15
            Me.columnEMail.AllowDBNull = false
            Me.columnEMail.MaxLength = 150
            Me.columnNacimento.AllowDBNull = false
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function NewClienteRow() As ClienteRow
            Return CType(Me.NewRow,ClienteRow)
        End Function
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Function NewRowFromBuilder(ByVal builder As System.Data.DataRowBuilder) As System.Data.DataRow
            Return New ClienteRow(builder)
        End Function
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Function GetRowType() As System.Type
            Return GetType(ClienteRow)
        End Function
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Sub OnRowChanged(ByVal e As System.Data.DataRowChangeEventArgs)
            MyBase.OnRowChanged(e)
            If (Not (Me.ClienteRowChangedEvent) Is Nothing) Then
                RaiseEvent ClienteRowChanged(Me, New ClienteRowChangeEvent(CType(e.Row,ClienteRow), e.Action))
            End If
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Sub OnRowChanging(ByVal e As System.Data.DataRowChangeEventArgs)
            MyBase.OnRowChanging(e)
            If (Not (Me.ClienteRowChangingEvent) Is Nothing) Then
                RaiseEvent ClienteRowChanging(Me, New ClienteRowChangeEvent(CType(e.Row,ClienteRow), e.Action))
            End If
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Sub OnRowDeleted(ByVal e As System.Data.DataRowChangeEventArgs)
            MyBase.OnRowDeleted(e)
            If (Not (Me.ClienteRowDeletedEvent) Is Nothing) Then
                RaiseEvent ClienteRowDeleted(Me, New ClienteRowChangeEvent(CType(e.Row,ClienteRow), e.Action))
            End If
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Sub OnRowDeleting(ByVal e As System.Data.DataRowChangeEventArgs)
            MyBase.OnRowDeleting(e)
            If (Not (Me.ClienteRowDeletingEvent) Is Nothing) Then
                RaiseEvent ClienteRowDeleting(Me, New ClienteRowChangeEvent(CType(e.Row,ClienteRow), e.Action))
            End If
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub RemoveClienteRow(ByVal row As ClienteRow)
            Me.Rows.Remove(row)
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Shared Function GetTypedTableSchema(ByVal xs As System.Xml.Schema.XmlSchemaSet) As System.Xml.Schema.XmlSchemaComplexType
            Dim type As System.Xml.Schema.XmlSchemaComplexType = New System.Xml.Schema.XmlSchemaComplexType
            Dim sequence As System.Xml.Schema.XmlSchemaSequence = New System.Xml.Schema.XmlSchemaSequence
            Dim ds As ClienteDataSet = New ClienteDataSet
            xs.Add(ds.GetSchemaSerializable)
            Dim any1 As System.Xml.Schema.XmlSchemaAny = New System.Xml.Schema.XmlSchemaAny
            any1.Namespace = "http://www.w3.org/2001/XMLSchema"
            any1.MinOccurs = New Decimal(0)
            any1.MaxOccurs = Decimal.MaxValue
            any1.ProcessContents = System.Xml.Schema.XmlSchemaContentProcessing.Lax
            sequence.Items.Add(any1)
            Dim any2 As System.Xml.Schema.XmlSchemaAny = New System.Xml.Schema.XmlSchemaAny
            any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1"
            any2.MinOccurs = New Decimal(1)
            any2.ProcessContents = System.Xml.Schema.XmlSchemaContentProcessing.Lax
            sequence.Items.Add(any2)
            Dim attribute1 As System.Xml.Schema.XmlSchemaAttribute = New System.Xml.Schema.XmlSchemaAttribute
            attribute1.Name = "namespace"
            attribute1.FixedValue = ds.Namespace
            type.Attributes.Add(attribute1)
            Dim attribute2 As System.Xml.Schema.XmlSchemaAttribute = New System.Xml.Schema.XmlSchemaAttribute
            attribute2.Name = "tableTypeName"
            attribute2.FixedValue = "ClienteDataTable"
            type.Attributes.Add(attribute2)
            type.Particle = sequence
            Return type
        End Function
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")>  _
    Partial Public Class ClienteRow
        Inherits System.Data.DataRow
        
        Private tableCliente As ClienteDataTable
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Friend Sub New(ByVal rb As System.Data.DataRowBuilder)
            MyBase.New(rb)
            Me.tableCliente = CType(Me.Table,ClienteDataTable)
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property CodigoCliente() As Integer
            Get
                Return CType(Me(Me.tableCliente.CodigoClienteColumn),Integer)
            End Get
            Set
                Me(Me.tableCliente.CodigoClienteColumn) = value
            End Set
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Nome() As String
            Get
                Return CType(Me(Me.tableCliente.NomeColumn),String)
            End Get
            Set
                Me(Me.tableCliente.NomeColumn) = value
            End Set
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Endereco() As String
            Get
                Return CType(Me(Me.tableCliente.EnderecoColumn),String)
            End Get
            Set
                Me(Me.tableCliente.EnderecoColumn) = value
            End Set
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Cidade() As String
            Get
                Return CType(Me(Me.tableCliente.CidadeColumn),String)
            End Get
            Set
                Me(Me.tableCliente.CidadeColumn) = value
            End Set
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Bairro() As String
            Get
                Return CType(Me(Me.tableCliente.BairroColumn),String)
            End Get
            Set
                Me(Me.tableCliente.BairroColumn) = value
            End Set
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Estado() As String
            Get
                Return CType(Me(Me.tableCliente.EstadoColumn),String)
            End Get
            Set
                Me(Me.tableCliente.EstadoColumn) = value
            End Set
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property CEP() As String
            Get
                Return CType(Me(Me.tableCliente.CEPColumn),String)
            End Get
            Set
                Me(Me.tableCliente.CEPColumn) = value
            End Set
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Telefone() As String
            Get
                Return CType(Me(Me.tableCliente.TelefoneColumn),String)
            End Get
            Set
                Me(Me.tableCliente.TelefoneColumn) = value
            End Set
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property EMail() As String
            Get
                Return CType(Me(Me.tableCliente.EMailColumn),String)
            End Get
            Set
                Me(Me.tableCliente.EMailColumn) = value
            End Set
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Nacimento() As Date
            Get
                Return CType(Me(Me.tableCliente.NacimentoColumn),Date)
            End Get
            Set
                Me(Me.tableCliente.NacimentoColumn) = value
            End Set
        End Property
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")>  _
    Public Class ClienteRowChangeEvent
        Inherits System.EventArgs
        
        Private eventRow As ClienteRow
        
        Private eventAction As System.Data.DataRowAction
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub New(ByVal row As ClienteRow, ByVal action As System.Data.DataRowAction)
            MyBase.New
            Me.eventRow = row
            Me.eventAction = action
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Row() As ClienteRow
            Get
                Return Me.eventRow
            End Get
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Action() As System.Data.DataRowAction
            Get
                Return Me.eventAction
            End Get
        End Property
    End Class
End Class

Namespace ClienteDataSetTableAdapters
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0"),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.ComponentModel.ToolboxItem(true),  _
     System.ComponentModel.DataObjectAttribute(true),  _
     System.ComponentModel.DesignerAttribute("Microsoft.VSDesigner.DataSource.Design.TableAdapterDesigner, Microsoft.VSDesigner"& _ 
        ", Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a"),  _
     System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter")>  _
    Partial Public Class ClienteTableAdapter
        Inherits System.ComponentModel.Component
        
        Private WithEvents _adapter As System.Data.SqlClient.SqlDataAdapter
        
        Private _connection As System.Data.SqlClient.SqlConnection
        
        Private _commandCollection() As System.Data.SqlClient.SqlCommand
        
        Private _clearBeforeFill As Boolean
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub New()
            MyBase.New
            Me.ClearBeforeFill = true
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Private ReadOnly Property Adapter() As System.Data.SqlClient.SqlDataAdapter
            Get
                If (Me._adapter Is Nothing) Then
                    Me.InitAdapter
                End If
                Return Me._adapter
            End Get
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Friend Property Connection() As System.Data.SqlClient.SqlConnection
            Get
                If (Me._connection Is Nothing) Then
                    Me.InitConnection
                End If
                Return Me._connection
            End Get
            Set
                Me._connection = value
                If (Not (Me.Adapter.InsertCommand) Is Nothing) Then
                    Me.Adapter.InsertCommand.Connection = value
                End If
                If (Not (Me.Adapter.DeleteCommand) Is Nothing) Then
                    Me.Adapter.DeleteCommand.Connection = value
                End If
                If (Not (Me.Adapter.UpdateCommand) Is Nothing) Then
                    Me.Adapter.UpdateCommand.Connection = value
                End If
                Dim i As Integer = 0
                Do While (i < Me.CommandCollection.Length)
                    If (Not (Me.CommandCollection(i)) Is Nothing) Then
                        CType(Me.CommandCollection(i),System.Data.SqlClient.SqlCommand).Connection = value
                    End If
                    i = (i + 1)
                Loop
            End Set
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected ReadOnly Property CommandCollection() As System.Data.SqlClient.SqlCommand()
            Get
                If (Me._commandCollection Is Nothing) Then
                    Me.InitCommandCollection
                End If
                Return Me._commandCollection
            End Get
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property ClearBeforeFill() As Boolean
            Get
                Return Me._clearBeforeFill
            End Get
            Set
                Me._clearBeforeFill = value
            End Set
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Private Sub InitAdapter()
            Me._adapter = New System.Data.SqlClient.SqlDataAdapter
            Dim tableMapping As System.Data.Common.DataTableMapping = New System.Data.Common.DataTableMapping
            tableMapping.SourceTable = "Table"
            tableMapping.DataSetTable = "Cliente"
            tableMapping.ColumnMappings.Add("CodigoCliente", "CodigoCliente")
            tableMapping.ColumnMappings.Add("Nome", "Nome")
            tableMapping.ColumnMappings.Add("Endereco", "Endereco")
            tableMapping.ColumnMappings.Add("Cidade", "Cidade")
            tableMapping.ColumnMappings.Add("Bairro", "Bairro")
            tableMapping.ColumnMappings.Add("Estado", "Estado")
            tableMapping.ColumnMappings.Add("CEP", "CEP")
            tableMapping.ColumnMappings.Add("Telefone", "Telefone")
            tableMapping.ColumnMappings.Add("EMail", "EMail")
            tableMapping.ColumnMappings.Add("Nacimento", "Nacimento")
            Me._adapter.TableMappings.Add(tableMapping)
            Me._adapter.DeleteCommand = New System.Data.SqlClient.SqlCommand
            Me._adapter.DeleteCommand.Connection = Me.Connection
            Me._adapter.DeleteCommand.CommandText = "DELETE FROM [dbo].[Cliente] WHERE (([CodigoCliente] = @Original_CodigoCliente) AN"& _ 
                "D ([Nome] = @Original_Nome) AND ([Endereco] = @Original_Endereco) AND ([Cidade] "& _ 
                "= @Original_Cidade) AND ([Bairro] = @Original_Bairro) AND ([Estado] = @Original_"& _ 
                "Estado) AND ([CEP] = @Original_CEP) AND ([Telefone] = @Original_Telefone) AND (["& _ 
                "EMail] = @Original_EMail) AND ([Nacimento] = @Original_Nacimento))"
            Me._adapter.DeleteCommand.CommandType = System.Data.CommandType.Text
            Me._adapter.DeleteCommand.Parameters.Add(New System.Data.SqlClient.SqlParameter("@Original_CodigoCliente", System.Data.SqlDbType.Int, 0, System.Data.ParameterDirection.Input, 0, 0, "CodigoCliente", System.Data.DataRowVersion.Original, false, Nothing, "", "", ""))
            Me._adapter.DeleteCommand.Parameters.Add(New System.Data.SqlClient.SqlParameter("@Original_Nome", System.Data.SqlDbType.NChar, 0, System.Data.ParameterDirection.Input, 0, 0, "Nome", System.Data.DataRowVersion.Original, false, Nothing, "", "", ""))
            Me._adapter.DeleteCommand.Parameters.Add(New System.Data.SqlClient.SqlParameter("@Original_Endereco", System.Data.SqlDbType.NChar, 0, System.Data.ParameterDirection.Input, 0, 0, "Endereco", System.Data.DataRowVersion.Original, false, Nothing, "", "", ""))
            Me._adapter.DeleteCommand.Parameters.Add(New System.Data.SqlClient.SqlParameter("@Original_Cidade", System.Data.SqlDbType.NChar, 0, System.Data.ParameterDirection.Input, 0, 0, "Cidade", System.Data.DataRowVersion.Original, false, Nothing, "", "", ""))
            Me._adapter.DeleteCommand.Parameters.Add(New System.Data.SqlClient.SqlParameter("@Original_Bairro", System.Data.SqlDbType.NChar, 0, System.Data.ParameterDirection.Input, 0, 0, "Bairro", System.Data.DataRowVersion.Original, false, Nothing, "", "", ""))
            Me._adapter.DeleteCommand.Parameters.Add(New System.Data.SqlClient.SqlParameter("@Original_Estado", System.Data.SqlDbType.NChar, 0, System.Data.ParameterDirection.Input, 0, 0, "Estado", System.Data.DataRowVersion.Original, false, Nothing, "", "", ""))
            Me._adapter.DeleteCommand.Parameters.Add(New System.Data.SqlClient.SqlParameter("@Original_CEP", System.Data.SqlDbType.NChar, 0, System.Data.ParameterDirection.Input, 0, 0, "CEP", System.Data.DataRowVersion.Original, false, Nothing, "", "", ""))
            Me._adapter.DeleteCommand.Parameters.Add(New System.Data.SqlClient.SqlParameter("@Original_Telefone", System.Data.SqlDbType.NChar, 0, System.Data.ParameterDirection.Input, 0, 0, "Telefone", System.Data.DataRowVersion.Original, false, Nothing, "", "", ""))
            Me._adapter.DeleteCommand.Parameters.Add(New System.Data.SqlClient.SqlParameter("@Original_EMail", System.Data.SqlDbType.NChar, 0, System.Data.ParameterDirection.Input, 0, 0, "EMail", System.Data.DataRowVersion.Original, false, Nothing, "", "", ""))
            Me._adapter.DeleteCommand.Parameters.Add(New System.Data.SqlClient.SqlParameter("@Original_Nacimento", System.Data.SqlDbType.SmallDateTime, 0, System.Data.ParameterDirection.Input, 0, 0, "Nacimento", System.Data.DataRowVersion.Original, false, Nothing, "", "", ""))
            Me._adapter.InsertCommand = New System.Data.SqlClient.SqlCommand
            Me._adapter.InsertCommand.Connection = Me.Connection
            Me._adapter.InsertCommand.CommandText = "INSERT INTO [dbo].[Cliente] ([Nome], [Endereco], [Cidade], [Bairro], [Estado], [C"& _ 
                "EP], [Telefone], [EMail], [Nacimento]) VALUES (@Nome, @Endereco, @Cidade, @Bairr"& _ 
                "o, @Estado, @CEP, @Telefone, @EMail, @Nacimento);"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"SELECT CodigoCliente, Nome, E"& _ 
                "ndereco, Cidade, Bairro, Estado, CEP, Telefone, EMail, Nacimento FROM Cliente WH"& _ 
                "ERE (CodigoCliente = SCOPE_IDENTITY())"
            Me._adapter.InsertCommand.CommandType = System.Data.CommandType.Text
            Me._adapter.InsertCommand.Parameters.Add(New System.Data.SqlClient.SqlParameter("@Nome", System.Data.SqlDbType.NChar, 0, System.Data.ParameterDirection.Input, 0, 0, "Nome", System.Data.DataRowVersion.Current, false, Nothing, "", "", ""))
            Me._adapter.InsertCommand.Parameters.Add(New System.Data.SqlClient.SqlParameter("@Endereco", System.Data.SqlDbType.NChar, 0, System.Data.ParameterDirection.Input, 0, 0, "Endereco", System.Data.DataRowVersion.Current, false, Nothing, "", "", ""))
            Me._adapter.InsertCommand.Parameters.Add(New System.Data.SqlClient.SqlParameter("@Cidade", System.Data.SqlDbType.NChar, 0, System.Data.ParameterDirection.Input, 0, 0, "Cidade", System.Data.DataRowVersion.Current, false, Nothing, "", "", ""))
            Me._adapter.InsertCommand.Parameters.Add(New System.Data.SqlClient.SqlParameter("@Bairro", System.Data.SqlDbType.NChar, 0, System.Data.ParameterDirection.Input, 0, 0, "Bairro", System.Data.DataRowVersion.Current, false, Nothing, "", "", ""))
            Me._adapter.InsertCommand.Parameters.Add(New System.Data.SqlClient.SqlParameter("@Estado", System.Data.SqlDbType.NChar, 0, System.Data.ParameterDirection.Input, 0, 0, "Estado", System.Data.DataRowVersion.Current, false, Nothing, "", "", ""))
            Me._adapter.InsertCommand.Parameters.Add(New System.Data.SqlClient.SqlParameter("@CEP", System.Data.SqlDbType.NChar, 0, System.Data.ParameterDirection.Input, 0, 0, "CEP", System.Data.DataRowVersion.Current, false, Nothing, "", "", ""))
            Me._adapter.InsertCommand.Parameters.Add(New System.Data.SqlClient.SqlParameter("@Telefone", System.Data.SqlDbType.NChar, 0, System.Data.ParameterDirection.Input, 0, 0, "Telefone", System.Data.DataRowVersion.Current, false, Nothing, "", "", ""))
            Me._adapter.InsertCommand.Parameters.Add(New System.Data.SqlClient.SqlParameter("@EMail", System.Data.SqlDbType.NChar, 0, System.Data.ParameterDirection.Input, 0, 0, "EMail", System.Data.DataRowVersion.Current, false, Nothing, "", "", ""))
            Me._adapter.InsertCommand.Parameters.Add(New System.Data.SqlClient.SqlParameter("@Nacimento", System.Data.SqlDbType.SmallDateTime, 0, System.Data.ParameterDirection.Input, 0, 0, "Nacimento", System.Data.DataRowVersion.Current, false, Nothing, "", "", ""))
            Me._adapter.UpdateCommand = New System.Data.SqlClient.SqlCommand
            Me._adapter.UpdateCommand.Connection = Me.Connection
            Me._adapter.UpdateCommand.CommandText = "UPDATE [dbo].[Cliente] SET [Nome] = @Nome, [Endereco] = @Endereco, [Cidade] = @Ci"& _ 
                "dade, [Bairro] = @Bairro, [Estado] = @Estado, [CEP] = @CEP, [Telefone] = @Telefo"& _ 
                "ne, [EMail] = @EMail, [Nacimento] = @Nacimento WHERE (([CodigoCliente] = @Origin"& _ 
                "al_CodigoCliente) AND ([Nome] = @Original_Nome) AND ([Endereco] = @Original_Ende"& _ 
                "reco) AND ([Cidade] = @Original_Cidade) AND ([Bairro] = @Original_Bairro) AND (["& _ 
                "Estado] = @Original_Estado) AND ([CEP] = @Original_CEP) AND ([Telefone] = @Origi"& _ 
                "nal_Telefone) AND ([EMail] = @Original_EMail) AND ([Nacimento] = @Original_Nacim"& _ 
                "ento));"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"SELECT CodigoCliente, Nome, Endereco, Cidade, Bairro, Estado, CEP, Tele"& _ 
                "fone, EMail, Nacimento FROM Cliente WHERE (CodigoCliente = @CodigoCliente)"
            Me._adapter.UpdateCommand.CommandType = System.Data.CommandType.Text
            Me._adapter.UpdateCommand.Parameters.Add(New System.Data.SqlClient.SqlParameter("@Nome", System.Data.SqlDbType.NChar, 0, System.Data.ParameterDirection.Input, 0, 0, "Nome", System.Data.DataRowVersion.Current, false, Nothing, "", "", ""))
            Me._adapter.UpdateCommand.Parameters.Add(New System.Data.SqlClient.SqlParameter("@Endereco", System.Data.SqlDbType.NChar, 0, System.Data.ParameterDirection.Input, 0, 0, "Endereco", System.Data.DataRowVersion.Current, false, Nothing, "", "", ""))
            Me._adapter.UpdateCommand.Parameters.Add(New System.Data.SqlClient.SqlParameter("@Cidade", System.Data.SqlDbType.NChar, 0, System.Data.ParameterDirection.Input, 0, 0, "Cidade", System.Data.DataRowVersion.Current, false, Nothing, "", "", ""))
            Me._adapter.UpdateCommand.Parameters.Add(New System.Data.SqlClient.SqlParameter("@Bairro", System.Data.SqlDbType.NChar, 0, System.Data.ParameterDirection.Input, 0, 0, "Bairro", System.Data.DataRowVersion.Current, false, Nothing, "", "", ""))
            Me._adapter.UpdateCommand.Parameters.Add(New System.Data.SqlClient.SqlParameter("@Estado", System.Data.SqlDbType.NChar, 0, System.Data.ParameterDirection.Input, 0, 0, "Estado", System.Data.DataRowVersion.Current, false, Nothing, "", "", ""))
            Me._adapter.UpdateCommand.Parameters.Add(New System.Data.SqlClient.SqlParameter("@CEP", System.Data.SqlDbType.NChar, 0, System.Data.ParameterDirection.Input, 0, 0, "CEP", System.Data.DataRowVersion.Current, false, Nothing, "", "", ""))
            Me._adapter.UpdateCommand.Parameters.Add(New System.Data.SqlClient.SqlParameter("@Telefone", System.Data.SqlDbType.NChar, 0, System.Data.ParameterDirection.Input, 0, 0, "Telefone", System.Data.DataRowVersion.Current, false, Nothing, "", "", ""))
            Me._adapter.UpdateCommand.Parameters.Add(New System.Data.SqlClient.SqlParameter("@EMail", System.Data.SqlDbType.NChar, 0, System.Data.ParameterDirection.Input, 0, 0, "EMail", System.Data.DataRowVersion.Current, false, Nothing, "", "", ""))
            Me._adapter.UpdateCommand.Parameters.Add(New System.Data.SqlClient.SqlParameter("@Nacimento", System.Data.SqlDbType.SmallDateTime, 0, System.Data.ParameterDirection.Input, 0, 0, "Nacimento", System.Data.DataRowVersion.Current, false, Nothing, "", "", ""))
            Me._adapter.UpdateCommand.Parameters.Add(New System.Data.SqlClient.SqlParameter("@Original_CodigoCliente", System.Data.SqlDbType.Int, 0, System.Data.ParameterDirection.Input, 0, 0, "CodigoCliente", System.Data.DataRowVersion.Original, false, Nothing, "", "", ""))
            Me._adapter.UpdateCommand.Parameters.Add(New System.Data.SqlClient.SqlParameter("@Original_Nome", System.Data.SqlDbType.NChar, 0, System.Data.ParameterDirection.Input, 0, 0, "Nome", System.Data.DataRowVersion.Original, false, Nothing, "", "", ""))
            Me._adapter.UpdateCommand.Parameters.Add(New System.Data.SqlClient.SqlParameter("@Original_Endereco", System.Data.SqlDbType.NChar, 0, System.Data.ParameterDirection.Input, 0, 0, "Endereco", System.Data.DataRowVersion.Original, false, Nothing, "", "", ""))
            Me._adapter.UpdateCommand.Parameters.Add(New System.Data.SqlClient.SqlParameter("@Original_Cidade", System.Data.SqlDbType.NChar, 0, System.Data.ParameterDirection.Input, 0, 0, "Cidade", System.Data.DataRowVersion.Original, false, Nothing, "", "", ""))
            Me._adapter.UpdateCommand.Parameters.Add(New System.Data.SqlClient.SqlParameter("@Original_Bairro", System.Data.SqlDbType.NChar, 0, System.Data.ParameterDirection.Input, 0, 0, "Bairro", System.Data.DataRowVersion.Original, false, Nothing, "", "", ""))
            Me._adapter.UpdateCommand.Parameters.Add(New System.Data.SqlClient.SqlParameter("@Original_Estado", System.Data.SqlDbType.NChar, 0, System.Data.ParameterDirection.Input, 0, 0, "Estado", System.Data.DataRowVersion.Original, false, Nothing, "", "", ""))
            Me._adapter.UpdateCommand.Parameters.Add(New System.Data.SqlClient.SqlParameter("@Original_CEP", System.Data.SqlDbType.NChar, 0, System.Data.ParameterDirection.Input, 0, 0, "CEP", System.Data.DataRowVersion.Original, false, Nothing, "", "", ""))
            Me._adapter.UpdateCommand.Parameters.Add(New System.Data.SqlClient.SqlParameter("@Original_Telefone", System.Data.SqlDbType.NChar, 0, System.Data.ParameterDirection.Input, 0, 0, "Telefone", System.Data.DataRowVersion.Original, false, Nothing, "", "", ""))
            Me._adapter.UpdateCommand.Parameters.Add(New System.Data.SqlClient.SqlParameter("@Original_EMail", System.Data.SqlDbType.NChar, 0, System.Data.ParameterDirection.Input, 0, 0, "EMail", System.Data.DataRowVersion.Original, false, Nothing, "", "", ""))
            Me._adapter.UpdateCommand.Parameters.Add(New System.Data.SqlClient.SqlParameter("@Original_Nacimento", System.Data.SqlDbType.SmallDateTime, 0, System.Data.ParameterDirection.Input, 0, 0, "Nacimento", System.Data.DataRowVersion.Original, false, Nothing, "", "", ""))
            Me._adapter.UpdateCommand.Parameters.Add(New System.Data.SqlClient.SqlParameter("@CodigoCliente", System.Data.SqlDbType.Int, 4, System.Data.ParameterDirection.Input, 0, 0, "CodigoCliente", System.Data.DataRowVersion.Current, false, Nothing, "", "", ""))
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Private Sub InitConnection()
            Me._connection = New System.Data.SqlClient.SqlConnection
            Me._connection.ConnectionString = Global.Locadora_Filmes.My.MySettings.Default.LocadoraConnectionString
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Private Sub InitCommandCollection()
            Me._commandCollection = New System.Data.SqlClient.SqlCommand(0) {}
            Me._commandCollection(0) = New System.Data.SqlClient.SqlCommand
            Me._commandCollection(0).Connection = Me.Connection
            Me._commandCollection(0).CommandText = "SELECT CodigoCliente, Nome, Endereco, Cidade, Bairro, Estado, CEP, Telefone, EMai"& _ 
                "l, Nacimento FROM dbo.Cliente"
            Me._commandCollection(0).CommandType = System.Data.CommandType.Text
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter"),  _
         System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Fill, true)>  _
        Public Overloads Overridable Function Fill(ByVal dataTable As ClienteDataSet.ClienteDataTable) As Integer
            Me.Adapter.SelectCommand = Me.CommandCollection(0)
            If (Me.ClearBeforeFill = true) Then
                dataTable.Clear
            End If
            Dim returnValue As Integer = Me.Adapter.Fill(dataTable)
            Return returnValue
        End Function
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter"),  _
         System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.[Select], true)>  _
        Public Overloads Overridable Function GetData() As ClienteDataSet.ClienteDataTable
            Me.Adapter.SelectCommand = Me.CommandCollection(0)
            Dim dataTable As ClienteDataSet.ClienteDataTable = New ClienteDataSet.ClienteDataTable
            Me.Adapter.Fill(dataTable)
            Return dataTable
        End Function
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter")>  _
        Public Overloads Overridable Function Update(ByVal dataTable As ClienteDataSet.ClienteDataTable) As Integer
            Return Me.Adapter.Update(dataTable)
        End Function
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter")>  _
        Public Overloads Overridable Function Update(ByVal dataSet As ClienteDataSet) As Integer
            Return Me.Adapter.Update(dataSet, "Cliente")
        End Function
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter")>  _
        Public Overloads Overridable Function Update(ByVal dataRow As System.Data.DataRow) As Integer
            Return Me.Adapter.Update(New System.Data.DataRow() {dataRow})
        End Function
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter")>  _
        Public Overloads Overridable Function Update(ByVal dataRows() As System.Data.DataRow) As Integer
            Return Me.Adapter.Update(dataRows)
        End Function
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter"),  _
         System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Delete, true)>  _
        Public Overloads Overridable Function Delete(ByVal Original_CodigoCliente As Integer, ByVal Original_Nome As String, ByVal Original_Endereco As String, ByVal Original_Cidade As String, ByVal Original_Bairro As String, ByVal Original_Estado As String, ByVal Original_CEP As String, ByVal Original_Telefone As String, ByVal Original_EMail As String, ByVal Original_Nacimento As Date) As Integer
            Me.Adapter.DeleteCommand.Parameters(0).Value = CType(Original_CodigoCliente,Integer)
            If (Original_Nome Is Nothing) Then
                Throw New System.ArgumentNullException("Original_Nome")
            Else
                Me.Adapter.DeleteCommand.Parameters(1).Value = CType(Original_Nome,String)
            End If
            If (Original_Endereco Is Nothing) Then
                Throw New System.ArgumentNullException("Original_Endereco")
            Else
                Me.Adapter.DeleteCommand.Parameters(2).Value = CType(Original_Endereco,String)
            End If
            If (Original_Cidade Is Nothing) Then
                Throw New System.ArgumentNullException("Original_Cidade")
            Else
                Me.Adapter.DeleteCommand.Parameters(3).Value = CType(Original_Cidade,String)
            End If
            If (Original_Bairro Is Nothing) Then
                Throw New System.ArgumentNullException("Original_Bairro")
            Else
                Me.Adapter.DeleteCommand.Parameters(4).Value = CType(Original_Bairro,String)
            End If
            If (Original_Estado Is Nothing) Then
                Throw New System.ArgumentNullException("Original_Estado")
            Else
                Me.Adapter.DeleteCommand.Parameters(5).Value = CType(Original_Estado,String)
            End If
            If (Original_CEP Is Nothing) Then
                Throw New System.ArgumentNullException("Original_CEP")
            Else
                Me.Adapter.DeleteCommand.Parameters(6).Value = CType(Original_CEP,String)
            End If
            If (Original_Telefone Is Nothing) Then
                Throw New System.ArgumentNullException("Original_Telefone")
            Else
                Me.Adapter.DeleteCommand.Parameters(7).Value = CType(Original_Telefone,String)
            End If
            If (Original_EMail Is Nothing) Then
                Throw New System.ArgumentNullException("Original_EMail")
            Else
                Me.Adapter.DeleteCommand.Parameters(8).Value = CType(Original_EMail,String)
            End If
            Me.Adapter.DeleteCommand.Parameters(9).Value = CType(Original_Nacimento,Date)
            Dim previousConnectionState As System.Data.ConnectionState = Me.Adapter.DeleteCommand.Connection.State
            If ((Me.Adapter.DeleteCommand.Connection.State And System.Data.ConnectionState.Open)  _
                        <> System.Data.ConnectionState.Open) Then
                Me.Adapter.DeleteCommand.Connection.Open
            End If
            Try 
                Dim returnValue As Integer = Me.Adapter.DeleteCommand.ExecuteNonQuery
                Return returnValue
            Finally
                If (previousConnectionState = System.Data.ConnectionState.Closed) Then
                    Me.Adapter.DeleteCommand.Connection.Close
                End If
            End Try
        End Function
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter"),  _
         System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Insert, true)>  _
        Public Overloads Overridable Function Insert(ByVal Nome As String, ByVal Endereco As String, ByVal Cidade As String, ByVal Bairro As String, ByVal Estado As String, ByVal CEP As String, ByVal Telefone As String, ByVal EMail As String, ByVal Nacimento As Date) As Integer
            If (Nome Is Nothing) Then
                Throw New System.ArgumentNullException("Nome")
            Else
                Me.Adapter.InsertCommand.Parameters(0).Value = CType(Nome,String)
            End If
            If (Endereco Is Nothing) Then
                Throw New System.ArgumentNullException("Endereco")
            Else
                Me.Adapter.InsertCommand.Parameters(1).Value = CType(Endereco,String)
            End If
            If (Cidade Is Nothing) Then
                Throw New System.ArgumentNullException("Cidade")
            Else
                Me.Adapter.InsertCommand.Parameters(2).Value = CType(Cidade,String)
            End If
            If (Bairro Is Nothing) Then
                Throw New System.ArgumentNullException("Bairro")
            Else
                Me.Adapter.InsertCommand.Parameters(3).Value = CType(Bairro,String)
            End If
            If (Estado Is Nothing) Then
                Throw New System.ArgumentNullException("Estado")
            Else
                Me.Adapter.InsertCommand.Parameters(4).Value = CType(Estado,String)
            End If
            If (CEP Is Nothing) Then
                Throw New System.ArgumentNullException("CEP")
            Else
                Me.Adapter.InsertCommand.Parameters(5).Value = CType(CEP,String)
            End If
            If (Telefone Is Nothing) Then
                Throw New System.ArgumentNullException("Telefone")
            Else
                Me.Adapter.InsertCommand.Parameters(6).Value = CType(Telefone,String)
            End If
            If (EMail Is Nothing) Then
                Throw New System.ArgumentNullException("EMail")
            Else
                Me.Adapter.InsertCommand.Parameters(7).Value = CType(EMail,String)
            End If
            Me.Adapter.InsertCommand.Parameters(8).Value = CType(Nacimento,Date)
            Dim previousConnectionState As System.Data.ConnectionState = Me.Adapter.InsertCommand.Connection.State
            If ((Me.Adapter.InsertCommand.Connection.State And System.Data.ConnectionState.Open)  _
                        <> System.Data.ConnectionState.Open) Then
                Me.Adapter.InsertCommand.Connection.Open
            End If
            Try 
                Dim returnValue As Integer = Me.Adapter.InsertCommand.ExecuteNonQuery
                Return returnValue
            Finally
                If (previousConnectionState = System.Data.ConnectionState.Closed) Then
                    Me.Adapter.InsertCommand.Connection.Close
                End If
            End Try
        End Function
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter"),  _
         System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Update, true)>  _
        Public Overloads Overridable Function Update( _
                    ByVal Nome As String,  _
                    ByVal Endereco As String,  _
                    ByVal Cidade As String,  _
                    ByVal Bairro As String,  _
                    ByVal Estado As String,  _
                    ByVal CEP As String,  _
                    ByVal Telefone As String,  _
                    ByVal EMail As String,  _
                    ByVal Nacimento As Date,  _
                    ByVal Original_CodigoCliente As Integer,  _
                    ByVal Original_Nome As String,  _
                    ByVal Original_Endereco As String,  _
                    ByVal Original_Cidade As String,  _
                    ByVal Original_Bairro As String,  _
                    ByVal Original_Estado As String,  _
                    ByVal Original_CEP As String,  _
                    ByVal Original_Telefone As String,  _
                    ByVal Original_EMail As String,  _
                    ByVal Original_Nacimento As Date,  _
                    ByVal CodigoCliente As Integer) As Integer
            If (Nome Is Nothing) Then
                Throw New System.ArgumentNullException("Nome")
            Else
                Me.Adapter.UpdateCommand.Parameters(0).Value = CType(Nome,String)
            End If
            If (Endereco Is Nothing) Then
                Throw New System.ArgumentNullException("Endereco")
            Else
                Me.Adapter.UpdateCommand.Parameters(1).Value = CType(Endereco,String)
            End If
            If (Cidade Is Nothing) Then
                Throw New System.ArgumentNullException("Cidade")
            Else
                Me.Adapter.UpdateCommand.Parameters(2).Value = CType(Cidade,String)
            End If
            If (Bairro Is Nothing) Then
                Throw New System.ArgumentNullException("Bairro")
            Else
                Me.Adapter.UpdateCommand.Parameters(3).Value = CType(Bairro,String)
            End If
            If (Estado Is Nothing) Then
                Throw New System.ArgumentNullException("Estado")
            Else
                Me.Adapter.UpdateCommand.Parameters(4).Value = CType(Estado,String)
            End If
            If (CEP Is Nothing) Then
                Throw New System.ArgumentNullException("CEP")
            Else
                Me.Adapter.UpdateCommand.Parameters(5).Value = CType(CEP,String)
            End If
            If (Telefone Is Nothing) Then
                Throw New System.ArgumentNullException("Telefone")
            Else
                Me.Adapter.UpdateCommand.Parameters(6).Value = CType(Telefone,String)
            End If
            If (EMail Is Nothing) Then
                Throw New System.ArgumentNullException("EMail")
            Else
                Me.Adapter.UpdateCommand.Parameters(7).Value = CType(EMail,String)
            End If
            Me.Adapter.UpdateCommand.Parameters(8).Value = CType(Nacimento,Date)
            Me.Adapter.UpdateCommand.Parameters(9).Value = CType(Original_CodigoCliente,Integer)
            If (Original_Nome Is Nothing) Then
                Throw New System.ArgumentNullException("Original_Nome")
            Else
                Me.Adapter.UpdateCommand.Parameters(10).Value = CType(Original_Nome,String)
            End If
            If (Original_Endereco Is Nothing) Then
                Throw New System.ArgumentNullException("Original_Endereco")
            Else
                Me.Adapter.UpdateCommand.Parameters(11).Value = CType(Original_Endereco,String)
            End If
            If (Original_Cidade Is Nothing) Then
                Throw New System.ArgumentNullException("Original_Cidade")
            Else
                Me.Adapter.UpdateCommand.Parameters(12).Value = CType(Original_Cidade,String)
            End If
            If (Original_Bairro Is Nothing) Then
                Throw New System.ArgumentNullException("Original_Bairro")
            Else
                Me.Adapter.UpdateCommand.Parameters(13).Value = CType(Original_Bairro,String)
            End If
            If (Original_Estado Is Nothing) Then
                Throw New System.ArgumentNullException("Original_Estado")
            Else
                Me.Adapter.UpdateCommand.Parameters(14).Value = CType(Original_Estado,String)
            End If
            If (Original_CEP Is Nothing) Then
                Throw New System.ArgumentNullException("Original_CEP")
            Else
                Me.Adapter.UpdateCommand.Parameters(15).Value = CType(Original_CEP,String)
            End If
            If (Original_Telefone Is Nothing) Then
                Throw New System.ArgumentNullException("Original_Telefone")
            Else
                Me.Adapter.UpdateCommand.Parameters(16).Value = CType(Original_Telefone,String)
            End If
            If (Original_EMail Is Nothing) Then
                Throw New System.ArgumentNullException("Original_EMail")
            Else
                Me.Adapter.UpdateCommand.Parameters(17).Value = CType(Original_EMail,String)
            End If
            Me.Adapter.UpdateCommand.Parameters(18).Value = CType(Original_Nacimento,Date)
            Me.Adapter.UpdateCommand.Parameters(19).Value = CType(CodigoCliente,Integer)
            Dim previousConnectionState As System.Data.ConnectionState = Me.Adapter.UpdateCommand.Connection.State
            If ((Me.Adapter.UpdateCommand.Connection.State And System.Data.ConnectionState.Open)  _
                        <> System.Data.ConnectionState.Open) Then
                Me.Adapter.UpdateCommand.Connection.Open
            End If
            Try 
                Dim returnValue As Integer = Me.Adapter.UpdateCommand.ExecuteNonQuery
                Return returnValue
            Finally
                If (previousConnectionState = System.Data.ConnectionState.Closed) Then
                    Me.Adapter.UpdateCommand.Connection.Close
                End If
            End Try
        End Function
    End Class
End Namespace
