'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.42
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System


<System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0"),  _
 Serializable(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.ComponentModel.ToolboxItem(true),  _
 System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema"),  _
 System.Xml.Serialization.XmlRootAttribute("FilmeDataSet"),  _
 System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")>  _
Partial Public Class FilmeDataSet
    Inherits System.Data.DataSet
    
    Private tableFilme As FilmeDataTable
    
    Private _schemaSerializationMode As System.Data.SchemaSerializationMode = System.Data.SchemaSerializationMode.IncludeSchema
    
    <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Public Sub New()
        MyBase.New
        Me.BeginInit
        Me.InitClass
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler MyBase.Tables.CollectionChanged, schemaChangedHandler
        AddHandler MyBase.Relations.CollectionChanged, schemaChangedHandler
        Me.EndInit
    End Sub
    
    <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Sub New(ByVal info As System.Runtime.Serialization.SerializationInfo, ByVal context As System.Runtime.Serialization.StreamingContext)
        MyBase.New(info, context, false)
        If (Me.IsBinarySerialized(info, context) = true) Then
            Me.InitVars(false)
            Dim schemaChangedHandler1 As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
            AddHandler Me.Tables.CollectionChanged, schemaChangedHandler1
            AddHandler Me.Relations.CollectionChanged, schemaChangedHandler1
            Return
        End If
        Dim strSchema As String = CType(info.GetValue("XmlSchema", GetType(String)),String)
        If (Me.DetermineSchemaSerializationMode(info, context) = System.Data.SchemaSerializationMode.IncludeSchema) Then
            Dim ds As System.Data.DataSet = New System.Data.DataSet
            ds.ReadXmlSchema(New System.Xml.XmlTextReader(New System.IO.StringReader(strSchema)))
            If (Not (ds.Tables("Filme")) Is Nothing) Then
                MyBase.Tables.Add(New FilmeDataTable(ds.Tables("Filme")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.ReadXmlSchema(New System.Xml.XmlTextReader(New System.IO.StringReader(strSchema)))
        End If
        Me.GetSerializationData(info, context)
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler MyBase.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    <System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     System.ComponentModel.Browsable(false),  _
     System.ComponentModel.DesignerSerializationVisibility(System.ComponentModel.DesignerSerializationVisibility.Content)>  _
    Public ReadOnly Property Filme() As FilmeDataTable
        Get
            Return Me.tableFilme
        End Get
    End Property
    
    <System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     System.ComponentModel.BrowsableAttribute(true),  _
     System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Visible)>  _
    Public Overrides Property SchemaSerializationMode() As System.Data.SchemaSerializationMode
        Get
            Return Me._schemaSerializationMode
        End Get
        Set
            Me._schemaSerializationMode = value
        End Set
    End Property
    
    <System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)>  _
    Public Shadows ReadOnly Property Tables() As System.Data.DataTableCollection
        Get
            Return MyBase.Tables
        End Get
    End Property
    
    <System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)>  _
    Public Shadows ReadOnly Property Relations() As System.Data.DataRelationCollection
        Get
            Return MyBase.Relations
        End Get
    End Property
    
    <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Overrides Sub InitializeDerivedDataSet()
        Me.BeginInit
        Me.InitClass
        Me.EndInit
    End Sub
    
    <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Public Overrides Function Clone() As System.Data.DataSet
        Dim cln As FilmeDataSet = CType(MyBase.Clone,FilmeDataSet)
        cln.InitVars
        cln.SchemaSerializationMode = Me.SchemaSerializationMode
        Return cln
    End Function
    
    <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Overrides Function ShouldSerializeTables() As Boolean
        Return false
    End Function
    
    <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Overrides Function ShouldSerializeRelations() As Boolean
        Return false
    End Function
    
    <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Overrides Sub ReadXmlSerializable(ByVal reader As System.Xml.XmlReader)
        If (Me.DetermineSchemaSerializationMode(reader) = System.Data.SchemaSerializationMode.IncludeSchema) Then
            Me.Reset
            Dim ds As System.Data.DataSet = New System.Data.DataSet
            ds.ReadXml(reader)
            If (Not (ds.Tables("Filme")) Is Nothing) Then
                MyBase.Tables.Add(New FilmeDataTable(ds.Tables("Filme")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.ReadXml(reader)
            Me.InitVars
        End If
    End Sub
    
    <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Overrides Function GetSchemaSerializable() As System.Xml.Schema.XmlSchema
        Dim stream As System.IO.MemoryStream = New System.IO.MemoryStream
        Me.WriteXmlSchema(New System.Xml.XmlTextWriter(stream, Nothing))
        stream.Position = 0
        Return System.Xml.Schema.XmlSchema.Read(New System.Xml.XmlTextReader(stream), Nothing)
    End Function
    
    <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Friend Overloads Sub InitVars()
        Me.InitVars(true)
    End Sub
    
    <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Friend Overloads Sub InitVars(ByVal initTable As Boolean)
        Me.tableFilme = CType(MyBase.Tables("Filme"),FilmeDataTable)
        If (initTable = true) Then
            If (Not (Me.tableFilme) Is Nothing) Then
                Me.tableFilme.InitVars
            End If
        End If
    End Sub
    
    <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Private Sub InitClass()
        Me.DataSetName = "FilmeDataSet"
        Me.Prefix = ""
        Me.Namespace = "http://tempuri.org/FilmeDataSet.xsd"
        Me.EnforceConstraints = true
        Me.SchemaSerializationMode = System.Data.SchemaSerializationMode.IncludeSchema
        Me.tableFilme = New FilmeDataTable
        MyBase.Tables.Add(Me.tableFilme)
    End Sub
    
    <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Private Function ShouldSerializeFilme() As Boolean
        Return false
    End Function
    
    <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Private Sub SchemaChanged(ByVal sender As Object, ByVal e As System.ComponentModel.CollectionChangeEventArgs)
        If (e.Action = System.ComponentModel.CollectionChangeAction.Remove) Then
            Me.InitVars
        End If
    End Sub
    
    <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Public Shared Function GetTypedDataSetSchema(ByVal xs As System.Xml.Schema.XmlSchemaSet) As System.Xml.Schema.XmlSchemaComplexType
        Dim ds As FilmeDataSet = New FilmeDataSet
        Dim type As System.Xml.Schema.XmlSchemaComplexType = New System.Xml.Schema.XmlSchemaComplexType
        Dim sequence As System.Xml.Schema.XmlSchemaSequence = New System.Xml.Schema.XmlSchemaSequence
        xs.Add(ds.GetSchemaSerializable)
        Dim any As System.Xml.Schema.XmlSchemaAny = New System.Xml.Schema.XmlSchemaAny
        any.Namespace = ds.Namespace
        sequence.Items.Add(any)
        type.Particle = sequence
        Return type
    End Function
    
    Public Delegate Sub FilmeRowChangeEventHandler(ByVal sender As Object, ByVal e As FilmeRowChangeEvent)
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0"),  _
     System.Serializable(),  _
     System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")>  _
    Partial Public Class FilmeDataTable
        Inherits System.Data.DataTable
        Implements System.Collections.IEnumerable
        
        Private columnCodigoFilme As System.Data.DataColumn
        
        Private columnTitulo As System.Data.DataColumn
        
        Private columnEstoque As System.Data.DataColumn
        
        Private columnGenero As System.Data.DataColumn
        
        Private columnMidia As System.Data.DataColumn
        
        Private columnClassificacao As System.Data.DataColumn
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub New()
            MyBase.New
            Me.TableName = "Filme"
            Me.BeginInit
            Me.InitClass
            Me.EndInit
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Friend Sub New(ByVal table As System.Data.DataTable)
            MyBase.New
            Me.TableName = table.TableName
            If (table.CaseSensitive <> table.DataSet.CaseSensitive) Then
                Me.CaseSensitive = table.CaseSensitive
            End If
            If (table.Locale.ToString <> table.DataSet.Locale.ToString) Then
                Me.Locale = table.Locale
            End If
            If (table.Namespace <> table.DataSet.Namespace) Then
                Me.Namespace = table.Namespace
            End If
            Me.Prefix = table.Prefix
            Me.MinimumCapacity = table.MinimumCapacity
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Sub New(ByVal info As System.Runtime.Serialization.SerializationInfo, ByVal context As System.Runtime.Serialization.StreamingContext)
            MyBase.New(info, context)
            Me.InitVars
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property CodigoFilmeColumn() As System.Data.DataColumn
            Get
                Return Me.columnCodigoFilme
            End Get
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property TituloColumn() As System.Data.DataColumn
            Get
                Return Me.columnTitulo
            End Get
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property EstoqueColumn() As System.Data.DataColumn
            Get
                Return Me.columnEstoque
            End Get
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property GeneroColumn() As System.Data.DataColumn
            Get
                Return Me.columnGenero
            End Get
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property MidiaColumn() As System.Data.DataColumn
            Get
                Return Me.columnMidia
            End Get
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property ClassificacaoColumn() As System.Data.DataColumn
            Get
                Return Me.columnClassificacao
            End Get
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         System.ComponentModel.Browsable(false)>  _
        Public ReadOnly Property Count() As Integer
            Get
                Return Me.Rows.Count
            End Get
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Default ReadOnly Property Item(ByVal index As Integer) As FilmeRow
            Get
                Return CType(Me.Rows(index),FilmeRow)
            End Get
        End Property
        
        Public Event FilmeRowChanging As FilmeRowChangeEventHandler
        
        Public Event FilmeRowChanged As FilmeRowChangeEventHandler
        
        Public Event FilmeRowDeleting As FilmeRowChangeEventHandler
        
        Public Event FilmeRowDeleted As FilmeRowChangeEventHandler
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Overloads Sub AddFilmeRow(ByVal row As FilmeRow)
            Me.Rows.Add(row)
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Overloads Function AddFilmeRow(ByVal CodigoFilme As Integer, ByVal Titulo As String, ByVal Estoque As Integer, ByVal Genero As String, ByVal Midia As String, ByVal Classificacao As String) As FilmeRow
            Dim rowFilmeRow As FilmeRow = CType(Me.NewRow,FilmeRow)
            rowFilmeRow.ItemArray = New Object() {CodigoFilme, Titulo, Estoque, Genero, Midia, Classificacao}
            Me.Rows.Add(rowFilmeRow)
            Return rowFilmeRow
        End Function
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function FindByCodigoFilme(ByVal CodigoFilme As Integer) As FilmeRow
            Return CType(Me.Rows.Find(New Object() {CodigoFilme}),FilmeRow)
        End Function
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Overridable Function GetEnumerator() As System.Collections.IEnumerator Implements System.Collections.IEnumerable.GetEnumerator
            Return Me.Rows.GetEnumerator
        End Function
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Overrides Function Clone() As System.Data.DataTable
            Dim cln As FilmeDataTable = CType(MyBase.Clone,FilmeDataTable)
            cln.InitVars
            Return cln
        End Function
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Function CreateInstance() As System.Data.DataTable
            Return New FilmeDataTable
        End Function
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Friend Sub InitVars()
            Me.columnCodigoFilme = MyBase.Columns("CodigoFilme")
            Me.columnTitulo = MyBase.Columns("Titulo")
            Me.columnEstoque = MyBase.Columns("Estoque")
            Me.columnGenero = MyBase.Columns("Genero")
            Me.columnMidia = MyBase.Columns("Midia")
            Me.columnClassificacao = MyBase.Columns("Classificacao")
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Private Sub InitClass()
            Me.columnCodigoFilme = New System.Data.DataColumn("CodigoFilme", GetType(Integer), Nothing, System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnCodigoFilme)
            Me.columnTitulo = New System.Data.DataColumn("Titulo", GetType(String), Nothing, System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnTitulo)
            Me.columnEstoque = New System.Data.DataColumn("Estoque", GetType(Integer), Nothing, System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnEstoque)
            Me.columnGenero = New System.Data.DataColumn("Genero", GetType(String), Nothing, System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnGenero)
            Me.columnMidia = New System.Data.DataColumn("Midia", GetType(String), Nothing, System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnMidia)
            Me.columnClassificacao = New System.Data.DataColumn("Classificacao", GetType(String), Nothing, System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnClassificacao)
            Me.Constraints.Add(New System.Data.UniqueConstraint("Constraint1", New System.Data.DataColumn() {Me.columnCodigoFilme}, true))
            Me.columnCodigoFilme.AllowDBNull = false
            Me.columnCodigoFilme.Unique = true
            Me.columnTitulo.AllowDBNull = false
            Me.columnTitulo.MaxLength = 50
            Me.columnEstoque.AllowDBNull = false
            Me.columnGenero.AllowDBNull = false
            Me.columnGenero.MaxLength = 50
            Me.columnMidia.AllowDBNull = false
            Me.columnMidia.MaxLength = 20
            Me.columnClassificacao.AllowDBNull = false
            Me.columnClassificacao.MaxLength = 15
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function NewFilmeRow() As FilmeRow
            Return CType(Me.NewRow,FilmeRow)
        End Function
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Function NewRowFromBuilder(ByVal builder As System.Data.DataRowBuilder) As System.Data.DataRow
            Return New FilmeRow(builder)
        End Function
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Function GetRowType() As System.Type
            Return GetType(FilmeRow)
        End Function
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Sub OnRowChanged(ByVal e As System.Data.DataRowChangeEventArgs)
            MyBase.OnRowChanged(e)
            If (Not (Me.FilmeRowChangedEvent) Is Nothing) Then
                RaiseEvent FilmeRowChanged(Me, New FilmeRowChangeEvent(CType(e.Row,FilmeRow), e.Action))
            End If
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Sub OnRowChanging(ByVal e As System.Data.DataRowChangeEventArgs)
            MyBase.OnRowChanging(e)
            If (Not (Me.FilmeRowChangingEvent) Is Nothing) Then
                RaiseEvent FilmeRowChanging(Me, New FilmeRowChangeEvent(CType(e.Row,FilmeRow), e.Action))
            End If
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Sub OnRowDeleted(ByVal e As System.Data.DataRowChangeEventArgs)
            MyBase.OnRowDeleted(e)
            If (Not (Me.FilmeRowDeletedEvent) Is Nothing) Then
                RaiseEvent FilmeRowDeleted(Me, New FilmeRowChangeEvent(CType(e.Row,FilmeRow), e.Action))
            End If
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Sub OnRowDeleting(ByVal e As System.Data.DataRowChangeEventArgs)
            MyBase.OnRowDeleting(e)
            If (Not (Me.FilmeRowDeletingEvent) Is Nothing) Then
                RaiseEvent FilmeRowDeleting(Me, New FilmeRowChangeEvent(CType(e.Row,FilmeRow), e.Action))
            End If
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub RemoveFilmeRow(ByVal row As FilmeRow)
            Me.Rows.Remove(row)
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Shared Function GetTypedTableSchema(ByVal xs As System.Xml.Schema.XmlSchemaSet) As System.Xml.Schema.XmlSchemaComplexType
            Dim type As System.Xml.Schema.XmlSchemaComplexType = New System.Xml.Schema.XmlSchemaComplexType
            Dim sequence As System.Xml.Schema.XmlSchemaSequence = New System.Xml.Schema.XmlSchemaSequence
            Dim ds As FilmeDataSet = New FilmeDataSet
            xs.Add(ds.GetSchemaSerializable)
            Dim any1 As System.Xml.Schema.XmlSchemaAny = New System.Xml.Schema.XmlSchemaAny
            any1.Namespace = "http://www.w3.org/2001/XMLSchema"
            any1.MinOccurs = New Decimal(0)
            any1.MaxOccurs = Decimal.MaxValue
            any1.ProcessContents = System.Xml.Schema.XmlSchemaContentProcessing.Lax
            sequence.Items.Add(any1)
            Dim any2 As System.Xml.Schema.XmlSchemaAny = New System.Xml.Schema.XmlSchemaAny
            any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1"
            any2.MinOccurs = New Decimal(1)
            any2.ProcessContents = System.Xml.Schema.XmlSchemaContentProcessing.Lax
            sequence.Items.Add(any2)
            Dim attribute1 As System.Xml.Schema.XmlSchemaAttribute = New System.Xml.Schema.XmlSchemaAttribute
            attribute1.Name = "namespace"
            attribute1.FixedValue = ds.Namespace
            type.Attributes.Add(attribute1)
            Dim attribute2 As System.Xml.Schema.XmlSchemaAttribute = New System.Xml.Schema.XmlSchemaAttribute
            attribute2.Name = "tableTypeName"
            attribute2.FixedValue = "FilmeDataTable"
            type.Attributes.Add(attribute2)
            type.Particle = sequence
            Return type
        End Function
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")>  _
    Partial Public Class FilmeRow
        Inherits System.Data.DataRow
        
        Private tableFilme As FilmeDataTable
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Friend Sub New(ByVal rb As System.Data.DataRowBuilder)
            MyBase.New(rb)
            Me.tableFilme = CType(Me.Table,FilmeDataTable)
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property CodigoFilme() As Integer
            Get
                Return CType(Me(Me.tableFilme.CodigoFilmeColumn),Integer)
            End Get
            Set
                Me(Me.tableFilme.CodigoFilmeColumn) = value
            End Set
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Titulo() As String
            Get
                Return CType(Me(Me.tableFilme.TituloColumn),String)
            End Get
            Set
                Me(Me.tableFilme.TituloColumn) = value
            End Set
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Estoque() As Integer
            Get
                Return CType(Me(Me.tableFilme.EstoqueColumn),Integer)
            End Get
            Set
                Me(Me.tableFilme.EstoqueColumn) = value
            End Set
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Genero() As String
            Get
                Return CType(Me(Me.tableFilme.GeneroColumn),String)
            End Get
            Set
                Me(Me.tableFilme.GeneroColumn) = value
            End Set
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Midia() As String
            Get
                Return CType(Me(Me.tableFilme.MidiaColumn),String)
            End Get
            Set
                Me(Me.tableFilme.MidiaColumn) = value
            End Set
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Classificacao() As String
            Get
                Return CType(Me(Me.tableFilme.ClassificacaoColumn),String)
            End Get
            Set
                Me(Me.tableFilme.ClassificacaoColumn) = value
            End Set
        End Property
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")>  _
    Public Class FilmeRowChangeEvent
        Inherits System.EventArgs
        
        Private eventRow As FilmeRow
        
        Private eventAction As System.Data.DataRowAction
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub New(ByVal row As FilmeRow, ByVal action As System.Data.DataRowAction)
            MyBase.New
            Me.eventRow = row
            Me.eventAction = action
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Row() As FilmeRow
            Get
                Return Me.eventRow
            End Get
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Action() As System.Data.DataRowAction
            Get
                Return Me.eventAction
            End Get
        End Property
    End Class
End Class

Namespace FilmeDataSetTableAdapters
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0"),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.ComponentModel.ToolboxItem(true),  _
     System.ComponentModel.DataObjectAttribute(true),  _
     System.ComponentModel.DesignerAttribute("Microsoft.VSDesigner.DataSource.Design.TableAdapterDesigner, Microsoft.VSDesigner"& _ 
        ", Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a"),  _
     System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter")>  _
    Partial Public Class FilmeTableAdapter
        Inherits System.ComponentModel.Component
        
        Private WithEvents _adapter As System.Data.SqlClient.SqlDataAdapter
        
        Private _connection As System.Data.SqlClient.SqlConnection
        
        Private _commandCollection() As System.Data.SqlClient.SqlCommand
        
        Private _clearBeforeFill As Boolean
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub New()
            MyBase.New
            Me.ClearBeforeFill = true
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Private ReadOnly Property Adapter() As System.Data.SqlClient.SqlDataAdapter
            Get
                If (Me._adapter Is Nothing) Then
                    Me.InitAdapter
                End If
                Return Me._adapter
            End Get
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Friend Property Connection() As System.Data.SqlClient.SqlConnection
            Get
                If (Me._connection Is Nothing) Then
                    Me.InitConnection
                End If
                Return Me._connection
            End Get
            Set
                Me._connection = value
                If (Not (Me.Adapter.InsertCommand) Is Nothing) Then
                    Me.Adapter.InsertCommand.Connection = value
                End If
                If (Not (Me.Adapter.DeleteCommand) Is Nothing) Then
                    Me.Adapter.DeleteCommand.Connection = value
                End If
                If (Not (Me.Adapter.UpdateCommand) Is Nothing) Then
                    Me.Adapter.UpdateCommand.Connection = value
                End If
                Dim i As Integer = 0
                Do While (i < Me.CommandCollection.Length)
                    If (Not (Me.CommandCollection(i)) Is Nothing) Then
                        CType(Me.CommandCollection(i),System.Data.SqlClient.SqlCommand).Connection = value
                    End If
                    i = (i + 1)
                Loop
            End Set
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected ReadOnly Property CommandCollection() As System.Data.SqlClient.SqlCommand()
            Get
                If (Me._commandCollection Is Nothing) Then
                    Me.InitCommandCollection
                End If
                Return Me._commandCollection
            End Get
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property ClearBeforeFill() As Boolean
            Get
                Return Me._clearBeforeFill
            End Get
            Set
                Me._clearBeforeFill = value
            End Set
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Private Sub InitAdapter()
            Me._adapter = New System.Data.SqlClient.SqlDataAdapter
            Dim tableMapping As System.Data.Common.DataTableMapping = New System.Data.Common.DataTableMapping
            tableMapping.SourceTable = "Table"
            tableMapping.DataSetTable = "Filme"
            tableMapping.ColumnMappings.Add("CodigoFilme", "CodigoFilme")
            tableMapping.ColumnMappings.Add("Titulo", "Titulo")
            tableMapping.ColumnMappings.Add("Estoque", "Estoque")
            tableMapping.ColumnMappings.Add("Genero", "Genero")
            tableMapping.ColumnMappings.Add("Midia", "Midia")
            tableMapping.ColumnMappings.Add("Classificacao", "Classificacao")
            Me._adapter.TableMappings.Add(tableMapping)
            Me._adapter.DeleteCommand = New System.Data.SqlClient.SqlCommand
            Me._adapter.DeleteCommand.Connection = Me.Connection
            Me._adapter.DeleteCommand.CommandText = "DELETE FROM [dbo].[Filme] WHERE (([CodigoFilme] = @Original_CodigoFilme) AND ([Ti"& _ 
                "tulo] = @Original_Titulo) AND ([Estoque] = @Original_Estoque) AND ([Genero] = @O"& _ 
                "riginal_Genero) AND ([Midia] = @Original_Midia) AND ([Classificacao] = @Original"& _ 
                "_Classificacao))"
            Me._adapter.DeleteCommand.CommandType = System.Data.CommandType.Text
            Me._adapter.DeleteCommand.Parameters.Add(New System.Data.SqlClient.SqlParameter("@Original_CodigoFilme", System.Data.SqlDbType.Int, 0, System.Data.ParameterDirection.Input, 0, 0, "CodigoFilme", System.Data.DataRowVersion.Original, false, Nothing, "", "", ""))
            Me._adapter.DeleteCommand.Parameters.Add(New System.Data.SqlClient.SqlParameter("@Original_Titulo", System.Data.SqlDbType.NChar, 0, System.Data.ParameterDirection.Input, 0, 0, "Titulo", System.Data.DataRowVersion.Original, false, Nothing, "", "", ""))
            Me._adapter.DeleteCommand.Parameters.Add(New System.Data.SqlClient.SqlParameter("@Original_Estoque", System.Data.SqlDbType.Int, 0, System.Data.ParameterDirection.Input, 0, 0, "Estoque", System.Data.DataRowVersion.Original, false, Nothing, "", "", ""))
            Me._adapter.DeleteCommand.Parameters.Add(New System.Data.SqlClient.SqlParameter("@Original_Genero", System.Data.SqlDbType.NChar, 0, System.Data.ParameterDirection.Input, 0, 0, "Genero", System.Data.DataRowVersion.Original, false, Nothing, "", "", ""))
            Me._adapter.DeleteCommand.Parameters.Add(New System.Data.SqlClient.SqlParameter("@Original_Midia", System.Data.SqlDbType.NChar, 0, System.Data.ParameterDirection.Input, 0, 0, "Midia", System.Data.DataRowVersion.Original, false, Nothing, "", "", ""))
            Me._adapter.DeleteCommand.Parameters.Add(New System.Data.SqlClient.SqlParameter("@Original_Classificacao", System.Data.SqlDbType.NChar, 0, System.Data.ParameterDirection.Input, 0, 0, "Classificacao", System.Data.DataRowVersion.Original, false, Nothing, "", "", ""))
            Me._adapter.InsertCommand = New System.Data.SqlClient.SqlCommand
            Me._adapter.InsertCommand.Connection = Me.Connection
            Me._adapter.InsertCommand.CommandText = "INSERT INTO [dbo].[Filme] ([CodigoFilme], [Titulo], [Estoque], [Genero], [Midia],"& _ 
                " [Classificacao]) VALUES (@CodigoFilme, @Titulo, @Estoque, @Genero, @Midia, @Cla"& _ 
                "ssificacao);"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"SELECT CodigoFilme, Titulo, Estoque, Genero, Midia, Classificacao "& _ 
                "FROM Filme WHERE (CodigoFilme = @CodigoFilme)"
            Me._adapter.InsertCommand.CommandType = System.Data.CommandType.Text
            Me._adapter.InsertCommand.Parameters.Add(New System.Data.SqlClient.SqlParameter("@CodigoFilme", System.Data.SqlDbType.Int, 0, System.Data.ParameterDirection.Input, 0, 0, "CodigoFilme", System.Data.DataRowVersion.Current, false, Nothing, "", "", ""))
            Me._adapter.InsertCommand.Parameters.Add(New System.Data.SqlClient.SqlParameter("@Titulo", System.Data.SqlDbType.NChar, 0, System.Data.ParameterDirection.Input, 0, 0, "Titulo", System.Data.DataRowVersion.Current, false, Nothing, "", "", ""))
            Me._adapter.InsertCommand.Parameters.Add(New System.Data.SqlClient.SqlParameter("@Estoque", System.Data.SqlDbType.Int, 0, System.Data.ParameterDirection.Input, 0, 0, "Estoque", System.Data.DataRowVersion.Current, false, Nothing, "", "", ""))
            Me._adapter.InsertCommand.Parameters.Add(New System.Data.SqlClient.SqlParameter("@Genero", System.Data.SqlDbType.NChar, 0, System.Data.ParameterDirection.Input, 0, 0, "Genero", System.Data.DataRowVersion.Current, false, Nothing, "", "", ""))
            Me._adapter.InsertCommand.Parameters.Add(New System.Data.SqlClient.SqlParameter("@Midia", System.Data.SqlDbType.NChar, 0, System.Data.ParameterDirection.Input, 0, 0, "Midia", System.Data.DataRowVersion.Current, false, Nothing, "", "", ""))
            Me._adapter.InsertCommand.Parameters.Add(New System.Data.SqlClient.SqlParameter("@Classificacao", System.Data.SqlDbType.NChar, 0, System.Data.ParameterDirection.Input, 0, 0, "Classificacao", System.Data.DataRowVersion.Current, false, Nothing, "", "", ""))
            Me._adapter.UpdateCommand = New System.Data.SqlClient.SqlCommand
            Me._adapter.UpdateCommand.Connection = Me.Connection
            Me._adapter.UpdateCommand.CommandText = "UPDATE [dbo].[Filme] SET [CodigoFilme] = @CodigoFilme, [Titulo] = @Titulo, [Estoq"& _ 
                "ue] = @Estoque, [Genero] = @Genero, [Midia] = @Midia, [Classificacao] = @Classif"& _ 
                "icacao WHERE (([CodigoFilme] = @Original_CodigoFilme) AND ([Titulo] = @Original_"& _ 
                "Titulo) AND ([Estoque] = @Original_Estoque) AND ([Genero] = @Original_Genero) AN"& _ 
                "D ([Midia] = @Original_Midia) AND ([Classificacao] = @Original_Classificacao));"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"SELECT CodigoFilme, Titulo, Estoque, Genero, Midia, Classificacao FROM Filme WH"& _ 
                "ERE (CodigoFilme = @CodigoFilme)"
            Me._adapter.UpdateCommand.CommandType = System.Data.CommandType.Text
            Me._adapter.UpdateCommand.Parameters.Add(New System.Data.SqlClient.SqlParameter("@CodigoFilme", System.Data.SqlDbType.Int, 0, System.Data.ParameterDirection.Input, 0, 0, "CodigoFilme", System.Data.DataRowVersion.Current, false, Nothing, "", "", ""))
            Me._adapter.UpdateCommand.Parameters.Add(New System.Data.SqlClient.SqlParameter("@Titulo", System.Data.SqlDbType.NChar, 0, System.Data.ParameterDirection.Input, 0, 0, "Titulo", System.Data.DataRowVersion.Current, false, Nothing, "", "", ""))
            Me._adapter.UpdateCommand.Parameters.Add(New System.Data.SqlClient.SqlParameter("@Estoque", System.Data.SqlDbType.Int, 0, System.Data.ParameterDirection.Input, 0, 0, "Estoque", System.Data.DataRowVersion.Current, false, Nothing, "", "", ""))
            Me._adapter.UpdateCommand.Parameters.Add(New System.Data.SqlClient.SqlParameter("@Genero", System.Data.SqlDbType.NChar, 0, System.Data.ParameterDirection.Input, 0, 0, "Genero", System.Data.DataRowVersion.Current, false, Nothing, "", "", ""))
            Me._adapter.UpdateCommand.Parameters.Add(New System.Data.SqlClient.SqlParameter("@Midia", System.Data.SqlDbType.NChar, 0, System.Data.ParameterDirection.Input, 0, 0, "Midia", System.Data.DataRowVersion.Current, false, Nothing, "", "", ""))
            Me._adapter.UpdateCommand.Parameters.Add(New System.Data.SqlClient.SqlParameter("@Classificacao", System.Data.SqlDbType.NChar, 0, System.Data.ParameterDirection.Input, 0, 0, "Classificacao", System.Data.DataRowVersion.Current, false, Nothing, "", "", ""))
            Me._adapter.UpdateCommand.Parameters.Add(New System.Data.SqlClient.SqlParameter("@Original_CodigoFilme", System.Data.SqlDbType.Int, 0, System.Data.ParameterDirection.Input, 0, 0, "CodigoFilme", System.Data.DataRowVersion.Original, false, Nothing, "", "", ""))
            Me._adapter.UpdateCommand.Parameters.Add(New System.Data.SqlClient.SqlParameter("@Original_Titulo", System.Data.SqlDbType.NChar, 0, System.Data.ParameterDirection.Input, 0, 0, "Titulo", System.Data.DataRowVersion.Original, false, Nothing, "", "", ""))
            Me._adapter.UpdateCommand.Parameters.Add(New System.Data.SqlClient.SqlParameter("@Original_Estoque", System.Data.SqlDbType.Int, 0, System.Data.ParameterDirection.Input, 0, 0, "Estoque", System.Data.DataRowVersion.Original, false, Nothing, "", "", ""))
            Me._adapter.UpdateCommand.Parameters.Add(New System.Data.SqlClient.SqlParameter("@Original_Genero", System.Data.SqlDbType.NChar, 0, System.Data.ParameterDirection.Input, 0, 0, "Genero", System.Data.DataRowVersion.Original, false, Nothing, "", "", ""))
            Me._adapter.UpdateCommand.Parameters.Add(New System.Data.SqlClient.SqlParameter("@Original_Midia", System.Data.SqlDbType.NChar, 0, System.Data.ParameterDirection.Input, 0, 0, "Midia", System.Data.DataRowVersion.Original, false, Nothing, "", "", ""))
            Me._adapter.UpdateCommand.Parameters.Add(New System.Data.SqlClient.SqlParameter("@Original_Classificacao", System.Data.SqlDbType.NChar, 0, System.Data.ParameterDirection.Input, 0, 0, "Classificacao", System.Data.DataRowVersion.Original, false, Nothing, "", "", ""))
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Private Sub InitConnection()
            Me._connection = New System.Data.SqlClient.SqlConnection
            Me._connection.ConnectionString = Global.Locadora_Filmes.My.MySettings.Default.LocadoraConnectionString
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Private Sub InitCommandCollection()
            Me._commandCollection = New System.Data.SqlClient.SqlCommand(0) {}
            Me._commandCollection(0) = New System.Data.SqlClient.SqlCommand
            Me._commandCollection(0).Connection = Me.Connection
            Me._commandCollection(0).CommandText = "SELECT CodigoFilme, Titulo, Estoque, Genero, Midia, Classificacao FROM dbo.Filme"
            Me._commandCollection(0).CommandType = System.Data.CommandType.Text
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter"),  _
         System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Fill, true)>  _
        Public Overloads Overridable Function Fill(ByVal dataTable As FilmeDataSet.FilmeDataTable) As Integer
            Me.Adapter.SelectCommand = Me.CommandCollection(0)
            If (Me.ClearBeforeFill = true) Then
                dataTable.Clear
            End If
            Dim returnValue As Integer = Me.Adapter.Fill(dataTable)
            Return returnValue
        End Function
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter"),  _
         System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.[Select], true)>  _
        Public Overloads Overridable Function GetData() As FilmeDataSet.FilmeDataTable
            Me.Adapter.SelectCommand = Me.CommandCollection(0)
            Dim dataTable As FilmeDataSet.FilmeDataTable = New FilmeDataSet.FilmeDataTable
            Me.Adapter.Fill(dataTable)
            Return dataTable
        End Function
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter")>  _
        Public Overloads Overridable Function Update(ByVal dataTable As FilmeDataSet.FilmeDataTable) As Integer
            Return Me.Adapter.Update(dataTable)
        End Function
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter")>  _
        Public Overloads Overridable Function Update(ByVal dataSet As FilmeDataSet) As Integer
            Return Me.Adapter.Update(dataSet, "Filme")
        End Function
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter")>  _
        Public Overloads Overridable Function Update(ByVal dataRow As System.Data.DataRow) As Integer
            Return Me.Adapter.Update(New System.Data.DataRow() {dataRow})
        End Function
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter")>  _
        Public Overloads Overridable Function Update(ByVal dataRows() As System.Data.DataRow) As Integer
            Return Me.Adapter.Update(dataRows)
        End Function
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter"),  _
         System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Delete, true)>  _
        Public Overloads Overridable Function Delete(ByVal Original_CodigoFilme As Integer, ByVal Original_Titulo As String, ByVal Original_Estoque As Integer, ByVal Original_Genero As String, ByVal Original_Midia As String, ByVal Original_Classificacao As String) As Integer
            Me.Adapter.DeleteCommand.Parameters(0).Value = CType(Original_CodigoFilme,Integer)
            If (Original_Titulo Is Nothing) Then
                Throw New System.ArgumentNullException("Original_Titulo")
            Else
                Me.Adapter.DeleteCommand.Parameters(1).Value = CType(Original_Titulo,String)
            End If
            Me.Adapter.DeleteCommand.Parameters(2).Value = CType(Original_Estoque,Integer)
            If (Original_Genero Is Nothing) Then
                Throw New System.ArgumentNullException("Original_Genero")
            Else
                Me.Adapter.DeleteCommand.Parameters(3).Value = CType(Original_Genero,String)
            End If
            If (Original_Midia Is Nothing) Then
                Throw New System.ArgumentNullException("Original_Midia")
            Else
                Me.Adapter.DeleteCommand.Parameters(4).Value = CType(Original_Midia,String)
            End If
            If (Original_Classificacao Is Nothing) Then
                Throw New System.ArgumentNullException("Original_Classificacao")
            Else
                Me.Adapter.DeleteCommand.Parameters(5).Value = CType(Original_Classificacao,String)
            End If
            Dim previousConnectionState As System.Data.ConnectionState = Me.Adapter.DeleteCommand.Connection.State
            If ((Me.Adapter.DeleteCommand.Connection.State And System.Data.ConnectionState.Open)  _
                        <> System.Data.ConnectionState.Open) Then
                Me.Adapter.DeleteCommand.Connection.Open
            End If
            Try 
                Dim returnValue As Integer = Me.Adapter.DeleteCommand.ExecuteNonQuery
                Return returnValue
            Finally
                If (previousConnectionState = System.Data.ConnectionState.Closed) Then
                    Me.Adapter.DeleteCommand.Connection.Close
                End If
            End Try
        End Function
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter"),  _
         System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Insert, true)>  _
        Public Overloads Overridable Function Insert(ByVal CodigoFilme As Integer, ByVal Titulo As String, ByVal Estoque As Integer, ByVal Genero As String, ByVal Midia As String, ByVal Classificacao As String) As Integer
            Me.Adapter.InsertCommand.Parameters(0).Value = CType(CodigoFilme,Integer)
            If (Titulo Is Nothing) Then
                Throw New System.ArgumentNullException("Titulo")
            Else
                Me.Adapter.InsertCommand.Parameters(1).Value = CType(Titulo,String)
            End If
            Me.Adapter.InsertCommand.Parameters(2).Value = CType(Estoque,Integer)
            If (Genero Is Nothing) Then
                Throw New System.ArgumentNullException("Genero")
            Else
                Me.Adapter.InsertCommand.Parameters(3).Value = CType(Genero,String)
            End If
            If (Midia Is Nothing) Then
                Throw New System.ArgumentNullException("Midia")
            Else
                Me.Adapter.InsertCommand.Parameters(4).Value = CType(Midia,String)
            End If
            If (Classificacao Is Nothing) Then
                Throw New System.ArgumentNullException("Classificacao")
            Else
                Me.Adapter.InsertCommand.Parameters(5).Value = CType(Classificacao,String)
            End If
            Dim previousConnectionState As System.Data.ConnectionState = Me.Adapter.InsertCommand.Connection.State
            If ((Me.Adapter.InsertCommand.Connection.State And System.Data.ConnectionState.Open)  _
                        <> System.Data.ConnectionState.Open) Then
                Me.Adapter.InsertCommand.Connection.Open
            End If
            Try 
                Dim returnValue As Integer = Me.Adapter.InsertCommand.ExecuteNonQuery
                Return returnValue
            Finally
                If (previousConnectionState = System.Data.ConnectionState.Closed) Then
                    Me.Adapter.InsertCommand.Connection.Close
                End If
            End Try
        End Function
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter"),  _
         System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Update, true)>  _
        Public Overloads Overridable Function Update(ByVal CodigoFilme As Integer, ByVal Titulo As String, ByVal Estoque As Integer, ByVal Genero As String, ByVal Midia As String, ByVal Classificacao As String, ByVal Original_CodigoFilme As Integer, ByVal Original_Titulo As String, ByVal Original_Estoque As Integer, ByVal Original_Genero As String, ByVal Original_Midia As String, ByVal Original_Classificacao As String) As Integer
            Me.Adapter.UpdateCommand.Parameters(0).Value = CType(CodigoFilme,Integer)
            If (Titulo Is Nothing) Then
                Throw New System.ArgumentNullException("Titulo")
            Else
                Me.Adapter.UpdateCommand.Parameters(1).Value = CType(Titulo,String)
            End If
            Me.Adapter.UpdateCommand.Parameters(2).Value = CType(Estoque,Integer)
            If (Genero Is Nothing) Then
                Throw New System.ArgumentNullException("Genero")
            Else
                Me.Adapter.UpdateCommand.Parameters(3).Value = CType(Genero,String)
            End If
            If (Midia Is Nothing) Then
                Throw New System.ArgumentNullException("Midia")
            Else
                Me.Adapter.UpdateCommand.Parameters(4).Value = CType(Midia,String)
            End If
            If (Classificacao Is Nothing) Then
                Throw New System.ArgumentNullException("Classificacao")
            Else
                Me.Adapter.UpdateCommand.Parameters(5).Value = CType(Classificacao,String)
            End If
            Me.Adapter.UpdateCommand.Parameters(6).Value = CType(Original_CodigoFilme,Integer)
            If (Original_Titulo Is Nothing) Then
                Throw New System.ArgumentNullException("Original_Titulo")
            Else
                Me.Adapter.UpdateCommand.Parameters(7).Value = CType(Original_Titulo,String)
            End If
            Me.Adapter.UpdateCommand.Parameters(8).Value = CType(Original_Estoque,Integer)
            If (Original_Genero Is Nothing) Then
                Throw New System.ArgumentNullException("Original_Genero")
            Else
                Me.Adapter.UpdateCommand.Parameters(9).Value = CType(Original_Genero,String)
            End If
            If (Original_Midia Is Nothing) Then
                Throw New System.ArgumentNullException("Original_Midia")
            Else
                Me.Adapter.UpdateCommand.Parameters(10).Value = CType(Original_Midia,String)
            End If
            If (Original_Classificacao Is Nothing) Then
                Throw New System.ArgumentNullException("Original_Classificacao")
            Else
                Me.Adapter.UpdateCommand.Parameters(11).Value = CType(Original_Classificacao,String)
            End If
            Dim previousConnectionState As System.Data.ConnectionState = Me.Adapter.UpdateCommand.Connection.State
            If ((Me.Adapter.UpdateCommand.Connection.State And System.Data.ConnectionState.Open)  _
                        <> System.Data.ConnectionState.Open) Then
                Me.Adapter.UpdateCommand.Connection.Open
            End If
            Try 
                Dim returnValue As Integer = Me.Adapter.UpdateCommand.ExecuteNonQuery
                Return returnValue
            Finally
                If (previousConnectionState = System.Data.ConnectionState.Closed) Then
                    Me.Adapter.UpdateCommand.Connection.Close
                End If
            End Try
        End Function
    End Class
End Namespace
